### ISSUE TITLE
Accessories missing tooltips + suggestion

### ISSUE THREAD

**Issue by BriceFable** [abluescarab/tModLoader-MultiLure#3]
Hello! I've been looking for multi-lure accessories and was delighted that you updated your mod to 1.4+!

Just a few things to note however. One game breaking issue, one minor issue, and some suggestions.

First and foremost, accessories simply cannot be equiped. They can be crafted, game doesn't crash or anything while in inventory, but I just can't equip them.

Second, for the minor issue, the tooltips might have been setup incorrectly on the fishing line accessories.
They're being displayed as "Mods.Multilure.FishingLine_Tooltip".

For the suggestion, just my personnal opinion, but the accessories might be adding too many lines too quickly?
Getting 99 extra lines at the very start of hardmode might be overdoing it for 10 bars and a hook.
I might be able to change that myself with a patch to add a sense of progression, but I'd rather have your approval first.

**Comment by abluescarab** [comment]
Hi, thanks for commenting! The latest version of the mod allows you to customize the number of lines you get from each accessory. Additionally, I modified the code that was preventing players from equipping the line, so it should work now. The latest version should also have fixed tooltips due to translation changes. Please open a new issue if any problems persist.
